Update gitActions.yml

diff --git a/.github/workflows/gitActions.yml b/.github/workflows/gitActions.yml
--- a/.github/workflows/gitActions.yml
+++ b/.github/workflows/gitActions.yml
@@ -36,4 +36,10 @@ jobs:
        echo "Regression Suite: ${{ github.event.inputs.testSuite }}"
        echo "Test Class: ${{ github.event.inputs.testClass }}" 
        ./gradlew test testcases/test1.java --info
-            
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+          name: Run Tests            # Name of the check run which will be created
+          path: build/test-results/test/TEST-*.xml    # Path to test results
+          reporter: java-junit        
